### ISSUE TITLE
安卓9.0监控后台失败，无法读取状态栏红包消息

### ISSUE THREAD

**Issue by lfglfg11** [LnJan/WechatLuckyMoneyGetter#3]
只能在当前聊天群窗口才能抢红包，在桌面或者其他软件，或者其他聊天群，即使通知栏有红包消息也不会点进去，请修复谢谢大佬

**Comment by LnJan** [comment]
>只能在当前聊天群窗口才能抢红包，在桌面或者其他软件，或者其他聊天群，即使通知栏有红包消息也不会点进去，请修复谢谢大佬

是Flyme吗？

**Comment by lfglfg11** [comment]
EMUI9.0

**Comment by LnJan** [comment]
> EMUI9.0

更新了一个版本。应该能解决Android9.0通知栏的问题

**Comment by lfglfg11** [comment]
是的，已经解决了！现在这个通知监控和https://github.com/ChineseCaptain/LuckyMoney.git这个项目的一致了！我刚开始是两个项目组合抢红包的，不过那个项目对点击红包和开的坐标不对应，，虽然通知方式改了，我还是不明所以，求大佬指导一下哪个文件哪些方法是获取通知栏的？

**Comment by LnJan** [comment]
他的跟我的是一样的。继承NotificationListenerService然后重写onNotificationPosted方法。这个方法是用来拦截消息通知的。我的是在HongbaoNotificationListenerService.java第88行可以获取到通知的内容。过去含有[微信红包]的信息就可以了。他的应该也是差不多。他的是在LuckyMoneyService.java的handeNotificationPosted方法中

**Comment by xuxuedong** [comment]
有个问题大佬，华为 nova 2，安卓8.0.0，下载的这个插件最新版v1.1.7，只在群聊界面中才能自动抢红包啊，在微信的对话界面或其他群聊界面，不能自动抢红包啊

**Comment by xuxuedong** [comment]
另外发现我这，来红包时，通知栏中的消息也没包含红包的字样啊，只是提示来一条微信消息，你们也是这样吗？

**Comment by LnJan** [comment]
> 感谢大佬，经测试，华为 nova 2，安卓8.0.0，下载的这个插件最新版v1.1.7，开启“通知显示消息详情”后，来红包时，通知栏中的消息包含红包字样，另外，在手机的主页中，以及在任意的群聊对话中，当来红包消息时，会自动进入指定群，打开红包，并点击红包，只是有一个问题，当在微信聊天列表页面中时，来红包消息时，不会自动抢红包，没有反应，，，再次感谢大佬的分享

**Comment by LnJan** [comment]
> > > 另外发现我这，来红包时，通知栏中的消息也没包含红包的字样啊，只是提示来一条微信消息，你们也是这样吗？
> > 
> > 
> > 可能是你设置了消息不显示之类的选项。我的小米也有这样的选项。正常的话要读到通知栏里面的消息才能判断有没有红包来了
> 
> 感谢大佬，经测试，华为 nova 2，安卓8.0.0，下载的这个插件最新版v1.1.7，开启“通知显示消息详情”后，来红包时，通知栏中的消息包含红包字样，另外，在手机的主页中，以及在任意的群聊对话中，当来红包消息时，会自动进入指定群，打开红包，并点击红包，只是有一个问题，当在微信聊天列表页面中时，来红包消息时，不会自动抢红包，没有反应，，，再次感谢大佬的分享

大佬称不上。我也是在学习Android。还望多多支持。你说的这个问题确实存在。主要是不同的手机截屏的位置有所不同。我现在还没有很好的解决方案。后续会继续跟进

**Comment by xuxuedong** [comment]
> > > > 另外发现我这，来红包时，通知栏中的消息也没包含红包的字样啊，只是提示来一条微信消息，你们也是这样吗？
> > > 
> > > 
> > > 可能是你设置了消息不显示之类的选项。我的小米也有这样的选项。正常的话要读到通知栏里面的消息才能判断有没有红包来了
> > 
> > 
> > 感谢大佬，经测试，华为 nova 2，安卓8.0.0，下载的这个插件最新版v1.1.7，开启“通知显示消息详情”后，来红包时，通知栏中的消息包含红包字样，另外，在手机的主页中，以及在任意的群聊对话中，当来红包消息时，会自动进入指定群，打开红包，并点击红包，只是有一个问题，当在微信聊天列表页面中时，来红包消息时，不会自动抢红包，没有反应，，，再次感谢大佬的分享
> 
> 大佬称不上。我也是在学习Android。还望多多支持。你说的这个问题确实存在。主要是不同的手机截屏的位置有所不同。我现在还没有很好的解决方案。后续会继续跟进

进一步测试，在其他app界面，以及息屏时，也可以自动抢红包，只不过息屏时不能有密码，以及不能有其他app的屏保，后续我会继续跟进测试的，必须支持：）

**Comment by LnJan** [comment]
> > > > > 另外发现我这，来红包时，通知栏中的消息也没包含红包的字样啊，只是提示来一条微信消息，你们也是这样吗？
> > > > 
> > > > 
> > > > 可能是你设置了消息不显示之类的选项。我的小米也有这样的选项。正常的话要读到通知栏里面的消息才能判断有没有红包来了
> > > 
> > > 
> > > 感谢大佬，经测试，华为 nova 2，安卓8.0.0，下载的这个插件最新版v1.1.7，开启“通知显示消息详情”后，来红包时，通知栏中的消息包含红包字样，另外，在手机的主页中，以及在任意的群聊对话中，当来红包消息时，会自动进入指定群，打开红包，并点击红包，只是有一个问题，当在微信聊天列表页面中时，来红包消息时，不会自动抢红包，没有反应，，，再次感谢大佬的分享
> > 
> > 
> > 大佬称不上。我也是在学习Android。还望多多支持。你说的这个问题确实存在。主要是不同的手机截屏的位置有所不同。我现在还没有很好的解决方案。后续会继续跟进
> 
> 进一步测试，在其他app界面，以及息屏时，也可以自动抢红包，只不过息屏时不能有密码，以及不能有其他app的屏保，后续我会继续跟进测试的，必须支持：）

是的。不可以有密码。谢谢哈！！！
