### ISSUE TITLE
原生安卓9.0应该是无效

### ISSUE THREAD

**Issue by JoseMourinh0** [LnJan/WechatLuckyMoneyGetter#4]
pixel 2xl，未root，9.0最新系统
每次打开你这个插件，就提示应用后台权限申请，什么省电策略之类，实际上网电量限制、流量限制全部都对这个插件设置了无效，也就是允许后台运行应用。

**Comment by LnJan** [comment]
>pixel 2xl，未root，9.0最新系统
每次打开你这个插件，就提示应用后台权限申请，什么省电策略之类，实际上网电量限制、流量限制全部都对这个插件设置了无效，也就是允许后台运行应用。

你的意思是就算不申请这些权限也可以后台运行是吗？

**Comment by LnJan** [comment]
> 我的意思是已经开了权限了，但是运行不正常，且一直提醒开启权限。

如果是原生的Android系统其实不需要后台运行权限也是可以的，你勾选了对话框不再提示的选项，对话框就不会再弹了。我申请这些权限是因为像MIUI这种系统会把后台服务杀掉。所以才要申请这么一个权限。我提了一个新版本，应该能解决9.0上消息通知读取的问题
